package com.globalfontmanager.service

import com.globalfontmanager.data.model.FontFile
import java.io.File

class FontModuleGenerator(private var stagingRoot: File) {
    fun updateStagingRoot(root: File) {
        stagingRoot = root
    }

    fun generate(font: FontFile, targets: List<SystemFontTarget>, profile: SystemFontProfile? = null): File {
        require(targets.isNotEmpty()) { "当前系统未找到可替换的目标字体" }
        val source = File(font.path)
        require(source.isFile && source.length() > 0) { "字体源文件不可用" }
        val module = stagingRoot.resolve(RootShellManager.MODULE_ID)
        if (module.exists()) module.deleteRecursively()
        module.mkdirs()
        module.resolve("system/fonts").mkdirs()
        targets.forEach { target ->
            val destination = module.resolve(moduleRelativePath(target.path))
            destination.parentFile?.mkdirs()
            source.copyTo(destination, overwrite = true)
        }
        profile?.configurationFiles?.forEach { (originalPath, content) ->
            val destination = module.resolve(moduleRelativePath(originalPath))
            destination.parentFile?.mkdirs()
            destination.writeText(content)
        }
        module.resolve("module.prop").writeText(
            "id=${RootShellManager.MODULE_ID}\n" +
                "name=Global Font Manager\n" +
                 "version=0.6.0\n" +
                 "versionCode=6\n" +
                 "minMagisk=26000\n" +
                 "minKernelSU=10940\n" +
                 "minAPatch=10500\n" +
                "author=Global Font Manager\n" +
                "description=System font overlay generated by Global Font Manager\n",
        )
        module.resolve("post-fs-data.sh").writeText("#!/system/bin/sh\n[ -d \"${'$'}MODPATH/system\" ] || touch \"${'$'}MODPATH/disable\"\n")
        module.resolve("service.sh").writeText("#!/system/bin/sh\n[ -r \"${'$'}MODPATH/module.prop\" ] || touch \"${'$'}MODPATH/disable\"\n")
        module.resolve("customize.sh").writeText("#!/system/bin/sh\nui_print \"Global Font Manager font overlay\"\n[ -d \"${'$'}MODPATH/system\" ] || abort \"Font overlay payload is missing\"\n")
        module.resolve("uninstall.sh").writeText("#!/system/bin/sh\nexit 0\n")
        listOf("post-fs-data.sh", "service.sh", "customize.sh", "uninstall.sh").forEach { module.resolve(it).setExecutable(true) }
        return module
    }

    fun generateRecoveryModule(backupDirectory: File): File {
        val module = stagingRoot.resolve("${RootShellManager.MODULE_ID}.recovery")
        if (module.exists()) module.deleteRecursively()
        module.mkdirs()
        module.resolve("module.prop").writeText(
            "id=${RootShellManager.MODULE_ID}.recovery\n" +
                 "name=Global Font Manager Recovery\n" +
                 "version=0.6.0\n" +
                "description=Recovery module for restoring backed up fonts\n",
        )
        module.resolve("uninstall.sh").writeText(
            "#!/system/bin/sh\n" +
                "MOD=${RootShellManager.quote(RootShellManager.MODULE_PATH)}\n" +
                "[ -d \"${'$'}MOD\" ] && touch \"${'$'}MOD/disable\"\n" +
                "exit 0\n",
        )
        module.resolve("emergency-restore.sh").writeText(
            "#!/system/bin/sh\n" +
                "touch ${RootShellManager.quote("${RootShellManager.MODULE_PATH}/disable")}\n" +
                "rm -rf ${RootShellManager.quote(RootShellManager.MODULE_PATH)}\n" +
                "exit 0\n",
        )
        module.resolve("backup-location.txt").writeText(backupDirectory.absolutePath)
        module.resolve("uninstall.sh").setExecutable(true)
        module.resolve("emergency-restore.sh").setExecutable(true)
        return module
    }

    private fun moduleRelativePath(originalPath: String): String {
        return when {
            originalPath.startsWith("/system/") -> originalPath.removePrefix("/")
            originalPath.startsWith("/product/") -> "system/product/${originalPath.removePrefix("/product/")}"
            originalPath.startsWith("/system_ext/") -> "system/system_ext/${originalPath.removePrefix("/system_ext/")}"
            originalPath.startsWith("/vendor/") -> "system/vendor/${originalPath.removePrefix("/vendor/")}"
            else -> error("不支持的系统字体路径")
        }
    }
}
