name: Build Global Font Manager APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Find Gradle Wrapper
        run: |
          find . -name gradlew -type f

      - name: Grant Gradle permission
        run: |
          chmod +x $(find . -name gradlew -type f | head -n 1)

      - name: Build Debug APK
        run: |
          GRADLEW=$(find . -name gradlew -type f | head -n 1)
          DIR=$(dirname "$GRADLEW")
          cd "$DIR"
          ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: global-font-manager-debug-apk
          path: "**/app/build/outputs/apk/debug/*.apk"
